// <auto-generated />
using System;
using AlpacaFleece.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlpacaFleece.Infrastructure.Migrations.InitialCreate
{
    [DbContext(typeof(TradingDbContext))]
    partial class TradingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("AlpacaFleece.Infrastructure.Data.BarEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Close")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Low")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "Timestamp")
                        .IsUnique();

                    b.ToTable("bars", (string)null);
                });

            modelBuilder.Entity("AlpacaFleece.Infrastructure.Data.BotStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("bot_state", (string)null);
                });

            modelBuilder.Entity("AlpacaFleece.Infrastructure.Data.CircuitBreakerStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastResetAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("circuit_breaker_state", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 0,
                            LastResetAt = new DateTimeOffset(new DateTime(2026, 2, 28, 19, 7, 12, 733, DateTimeKind.Unspecified).AddTicks(3940), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AlpacaFleece.Infrastructure.Data.DrawdownStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentDrawdownPct")
                        .HasPrecision(10, 6)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastPeakResetTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ManualRecoveryRequested")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PeakEquity")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("drawdown_state", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentDrawdownPct = 0m,
                            LastPeakResetTime = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastUpdated = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Level = "Normal",
                            ManualRecoveryRequested = false,
                            PeakEquity = 0m
                        });
                });

            modelBuilder.Entity("AlpacaFleece.Infrastructure.Data.EquityCurveEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CashBalance")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CumulativePnl")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DailyPnl")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PortfolioValue")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .IsUnique();

                    b.ToTable("equity_curve", (string)null);
                });

            modelBuilder.Entity("AlpacaFleece.Infrastructure.Data.ExitAttemptEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("NextRetryAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("exit_attempts", (string)null);
                });

            modelBuilder.Entity("AlpacaFleece.Infrastructure.Data.FillEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlpacaOrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("FillDedupeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FilledAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FilledPrice")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("FilledQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlpacaOrderId", "FillDedupeKey")
                        .IsUnique();

                    b.ToTable("fills", (string)null);
                });

            modelBuilder.Entity("AlpacaFleece.Infrastructure.Data.OrderIntentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlpacaOrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LimitPrice")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId")
                        .IsUnique();

                    b.ToTable("order_intents", (string)null);
                });

            modelBuilder.Entity("AlpacaFleece.Infrastructure.Data.PositionSnapshotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AverageEntryPrice")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("SnapshotAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnrealizedPnl")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "SnapshotAt");

                    b.ToTable("position_snapshots", (string)null);
                });

            modelBuilder.Entity("AlpacaFleece.Infrastructure.Data.PositionTrackingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AtrValue")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastUpdateAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TrailingStopPrice")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("position_tracking", (string)null);
                });

            modelBuilder.Entity("AlpacaFleece.Infrastructure.Data.ReconciliationReportEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdersProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ReportDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPnl")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TradesCompleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReportDate");

                    b.ToTable("reconciliation_reports", (string)null);
                });

            modelBuilder.Entity("AlpacaFleece.Infrastructure.Data.SchemaMetaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("schema_meta", (string)null);
                });

            modelBuilder.Entity("AlpacaFleece.Infrastructure.Data.SignalGateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastAcceptedBarTs")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastAcceptedTs")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GateName")
                        .IsUnique();

                    b.ToTable("signal_gates", (string)null);
                });

            modelBuilder.Entity("AlpacaFleece.Infrastructure.Data.TradeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlpacaOrderId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AverageEntryPrice")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EnteredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExitedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilledQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitialQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RealizedPnl")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Symbol");

                    b.ToTable("trades", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
